title: Software Defect Prediciton Using Rich Contextualized Language Use Vectors
description: Software Technology Lab, Queen's University, Kingston, Canada
show_downloads: true
google_analytics:
theme: jekyll-theme-leap-day
include:
  - "_img"
